gitea:
  config:
    database:
      type: postgres
  additionalConfigFromEnvs:
    - name: GITEA__DATABASE__HOST
      valueFrom:
        secretKeyRef:
          name: pgsql-secret
          key: host
    - name: GITEA__DATABASE__PASSWD
      valueFrom:
        secretKeyRef:
          name: pgsql-secret
          key: password
    - name: GITEA__DATABASE__NAME
      valueFrom:
        secretKeyRef:
          name: pgsql-secret
          key: name
    - name: GITEA__DATABASE__USER
      valueFrom:
        secretKeyRef:
          name: pgsql-secret
          key: user
postgresql:
  enabled: false
postgresql-ha:
  enabled: false
