resources:
  - "./namespace.yaml"
  - "./pgsql_secret-sealed.yaml"
  - "./helm_repo.yaml"
  - "./helm_release.yaml"
  - "./pg_db.yaml"

configMapGenerator:
  - name: gitea-values
    files:
      - values.yaml

# secretGenerator:
#   - name: pgsql-secrets
#     files:
#       - pgsql_secrets.yaml=pgsql_secret-sealed.yaml

configurations:
  - "./kustomizeconfig.yaml"
