resources:
  - "./namespace.yaml"
  - "./pgsql_secret-sealed.yaml"
  - "./helm_repo.yaml"
  - "./helm_release.yaml"
  - "./pg_db.yaml"

configMapGenerator:
  - name: gitea-values
    namespace: gitea
    files:
      - values.yaml

configurations:
  - "./kustomizeconfig.yaml"
