gitea:
  config:
    database:
      DB_TYPE: postgres
      HOST: shared-pgsql-rw.pgsql:5432
  additionalConfigSources:
    - secret:
      secretName: pgsql-secret
postgresql:
  enabled: false
postgresql-ha:
  enabled: false
