apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmChart
metadata:
  name: ingress-nginx
  namespace: nginx
spec:
  chart: nginx-ingress
  version: 4.0.x
  interval: 8h
  sourceRef:
    kind: HelmRepository
    name: ingress-nginx
    namespace: nginx
  values:
    controller:
      publishService:
        enabled: true
