apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: ingress-nginx
  namespace: nginx
spec:
  chart: nginx-ingress
  version: 2.0.x
  interval: 8h
  sourceRef:
    kind: HelmRepository
    name: ingress-nginx
