apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: nginx
spec:
  releaseName: ingress-nginx
  chartRef:
    kind: HelmChart
    name: ingress-nginx
  # chart:
  #   spec:
  #     chart: nginx-ingress
  #     sourceRef:
  #       kind: HelmRepository
  #       name: ingress-nginx
  #     interval: 1h
  interval: 1h
  #
  # values:
  #   controller:
  #     kind: DaemonSet
  #     service:
  #       type: LoadBalancer
